// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace fusiondash {
	
	
	public partial class Default {
		
		protected System.Web.UI.HtmlControls.HtmlForm formSettings;
		
		protected System.Web.UI.WebControls.Label labelUpTime;
		
		protected System.Web.UI.WebControls.Label labelSN;
		
		protected System.Web.UI.WebControls.TextBox textBoxNick;
		
		protected System.Web.UI.WebControls.Label labelSpeedAvg;
		
		protected System.Web.UI.WebControls.Label labelSpeedCur;
		
		protected System.Web.UI.WebControls.Label labelBoardTemp;
		
		protected System.Web.UI.WebControls.Label labelChipTemp;
		
		protected System.Web.UI.WebControls.TextBox textBoxMinerPass;
		
		protected System.Web.UI.WebControls.TextBox textBoxMinerPass2;
		
		protected System.Web.UI.WebControls.DropDownList dropdownListVolt;
		
		protected System.Web.UI.WebControls.DropDownList dropdownListFreq;
		
		protected System.Web.UI.WebControls.TextBox textBoxPool1Url;
		
		protected System.Web.UI.WebControls.TextBox textBoxPool1Port;
		
		protected System.Web.UI.WebControls.TextBox textBoxPool1User;
		
		protected System.Web.UI.WebControls.TextBox textBoxPool1Pass;
		
		protected System.Web.UI.WebControls.TextBox textBoxPool2Url;
		
		protected System.Web.UI.WebControls.TextBox textBoxPool2Port;
		
		protected System.Web.UI.WebControls.TextBox textBoxPool2User;
		
		protected System.Web.UI.WebControls.TextBox textBoxPool2Pass;
		
		protected System.Web.UI.WebControls.TextBox textBoxPool3Url;
		
		protected System.Web.UI.WebControls.TextBox textBoxPool3Port;
		
		protected System.Web.UI.WebControls.TextBox textBoxPool3User;
		
		protected System.Web.UI.WebControls.TextBox textBoxPool3Pass;
		
		protected System.Web.UI.WebControls.DropDownList dropdownListWiredDHCP;
		
		protected System.Web.UI.WebControls.TextBox textBoxWiredIP;
		
		protected System.Web.UI.WebControls.TextBox textBoxWiredSubnetMask;
		
		protected System.Web.UI.WebControls.TextBox textBoxWiredRouter;
		
		protected System.Web.UI.WebControls.TextBox textBoxWiredDNS1;
		
		protected System.Web.UI.WebControls.TextBox textBoxWiredDNS2;
		
		protected System.Web.UI.WebControls.Button buttonBlink;
		
		protected System.Web.UI.WebControls.Button buttonShutdown;
		
		protected System.Web.UI.WebControls.Button buttonSave;
	}
}
