// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace fusiondash {
	
	
	public partial class Details {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.Label labelUpTime;
		
		protected System.Web.UI.WebControls.Label labelSpeedAvg;
		
		protected System.Web.UI.WebControls.Label labelSpeedCur;
		
		protected System.Web.UI.WebControls.Label labelBoardTemp;
		
		protected System.Web.UI.WebControls.Label labelChipTemp;
		
		protected System.Web.UI.WebControls.Table tablePool;
		
		protected System.Web.UI.WebControls.Table tableChipTemp;
		
		protected System.Web.UI.WebControls.Label labelAccepted;
		
		protected System.Web.UI.WebControls.Table tableAccepted;
		
		protected System.Web.UI.WebControls.Label labelHwError;
		
		protected System.Web.UI.WebControls.Table tableHwError;
		
		protected System.Web.UI.WebControls.Table tableTotal;
	}
}
