// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace fusionweb {
	
	
	public partial class Default {
		
		protected System.Web.UI.HtmlControls.HtmlForm formSettings;
		
		protected System.Web.UI.WebControls.Label labelTotalMiners;
		
		protected System.Web.UI.WebControls.Label labelActiveMiners;
		
		protected System.Web.UI.WebControls.Label labelTotalSpeed;
		
		protected System.Web.UI.WebControls.Label labelAverageSpeed;
		
		protected System.Web.UI.WebControls.Label labelOldestVersion;
		
		protected System.Web.UI.WebControls.Label labelNewestVersion;
		
		protected System.Web.UI.WebControls.Table tableSlowMiners;
	}
}
