/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace FusionMiner.Thrift
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class BoardStatus : TBase
  {
    private List<ChipStatus> _Chip;
    private double _Temperature;

    public List<ChipStatus> Chip
    {
      get
      {
        return _Chip;
      }
      set
      {
        __isset.Chip = true;
        this._Chip = value;
      }
    }

    public double Temperature
    {
      get
      {
        return _Temperature;
      }
      set
      {
        __isset.Temperature = true;
        this._Temperature = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool Chip;
      public bool Temperature;
    }

    public BoardStatus() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.List) {
              {
                Chip = new List<ChipStatus>();
                TList _list8 = iprot.ReadListBegin();
                for( int _i9 = 0; _i9 < _list8.Count; ++_i9)
                {
                  ChipStatus _elem10 = new ChipStatus();
                  _elem10 = new ChipStatus();
                  _elem10.Read(iprot);
                  Chip.Add(_elem10);
                }
                iprot.ReadListEnd();
              }
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.Double) {
              Temperature = iprot.ReadDouble();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("BoardStatus");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (Chip != null && __isset.Chip) {
        field.Name = "Chip";
        field.Type = TType.List;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteListBegin(new TList(TType.Struct, Chip.Count));
          foreach (ChipStatus _iter11 in Chip)
          {
            _iter11.Write(oprot);
          }
          oprot.WriteListEnd();
        }
        oprot.WriteFieldEnd();
      }
      if (__isset.Temperature) {
        field.Name = "Temperature";
        field.Type = TType.Double;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        oprot.WriteDouble(Temperature);
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder __sb = new StringBuilder("BoardStatus(");
      bool __first = true;
      if (Chip != null && __isset.Chip) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Chip: ");
        __sb.Append(Chip);
      }
      if (__isset.Temperature) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Temperature: ");
        __sb.Append(Temperature);
      }
      __sb.Append(")");
      return __sb.ToString();
    }

  }

}
