/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace FusionMiner.Thrift
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class ChipStatus : TBase
  {
    private List<CoreStatus> _Core;
    private double _Temperature;

    public List<CoreStatus> Core
    {
      get
      {
        return _Core;
      }
      set
      {
        __isset.Core = true;
        this._Core = value;
      }
    }

    public double Temperature
    {
      get
      {
        return _Temperature;
      }
      set
      {
        __isset.Temperature = true;
        this._Temperature = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool Core;
      public bool Temperature;
    }

    public ChipStatus() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.List) {
              {
                Core = new List<CoreStatus>();
                TList _list4 = iprot.ReadListBegin();
                for( int _i5 = 0; _i5 < _list4.Count; ++_i5)
                {
                  CoreStatus _elem6 = new CoreStatus();
                  _elem6 = new CoreStatus();
                  _elem6.Read(iprot);
                  Core.Add(_elem6);
                }
                iprot.ReadListEnd();
              }
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.Double) {
              Temperature = iprot.ReadDouble();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("ChipStatus");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (Core != null && __isset.Core) {
        field.Name = "Core";
        field.Type = TType.List;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteListBegin(new TList(TType.Struct, Core.Count));
          foreach (CoreStatus _iter7 in Core)
          {
            _iter7.Write(oprot);
          }
          oprot.WriteListEnd();
        }
        oprot.WriteFieldEnd();
      }
      if (__isset.Temperature) {
        field.Name = "Temperature";
        field.Type = TType.Double;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        oprot.WriteDouble(Temperature);
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder __sb = new StringBuilder("ChipStatus(");
      bool __first = true;
      if (Core != null && __isset.Core) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Core: ");
        __sb.Append(Core);
      }
      if (__isset.Temperature) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Temperature: ");
        __sb.Append(Temperature);
      }
      __sb.Append(")");
      return __sb.ToString();
    }

  }

}
