/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace FusionMiner.Thrift
{
  public enum HardwareType
  {
    DigBigSerial = 0,
    DigBigSPI = 1,
    DigBigSPIV2 = 2,
  }
}
