/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace FusionMiner.Thrift
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class HardwareStatus : TBase
  {
    private int _DeviceNumber;
    private string _DeviceName;
    private List<BoardStatus> _Board;
    private int _Difficulty;

    public int DeviceNumber
    {
      get
      {
        return _DeviceNumber;
      }
      set
      {
        __isset.DeviceNumber = true;
        this._DeviceNumber = value;
      }
    }

    public string DeviceName
    {
      get
      {
        return _DeviceName;
      }
      set
      {
        __isset.DeviceName = true;
        this._DeviceName = value;
      }
    }

    public List<BoardStatus> Board
    {
      get
      {
        return _Board;
      }
      set
      {
        __isset.Board = true;
        this._Board = value;
      }
    }

    public int Difficulty
    {
      get
      {
        return _Difficulty;
      }
      set
      {
        __isset.Difficulty = true;
        this._Difficulty = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool DeviceNumber;
      public bool DeviceName;
      public bool Board;
      public bool Difficulty;
    }

    public HardwareStatus() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.I32) {
              DeviceNumber = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.String) {
              DeviceName = iprot.ReadString();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 3:
            if (field.Type == TType.List) {
              {
                Board = new List<BoardStatus>();
                TList _list12 = iprot.ReadListBegin();
                for( int _i13 = 0; _i13 < _list12.Count; ++_i13)
                {
                  BoardStatus _elem14 = new BoardStatus();
                  _elem14 = new BoardStatus();
                  _elem14.Read(iprot);
                  Board.Add(_elem14);
                }
                iprot.ReadListEnd();
              }
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 4:
            if (field.Type == TType.I32) {
              Difficulty = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("HardwareStatus");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (__isset.DeviceNumber) {
        field.Name = "DeviceNumber";
        field.Type = TType.I32;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(DeviceNumber);
        oprot.WriteFieldEnd();
      }
      if (DeviceName != null && __isset.DeviceName) {
        field.Name = "DeviceName";
        field.Type = TType.String;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(DeviceName);
        oprot.WriteFieldEnd();
      }
      if (Board != null && __isset.Board) {
        field.Name = "Board";
        field.Type = TType.List;
        field.ID = 3;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteListBegin(new TList(TType.Struct, Board.Count));
          foreach (BoardStatus _iter15 in Board)
          {
            _iter15.Write(oprot);
          }
          oprot.WriteListEnd();
        }
        oprot.WriteFieldEnd();
      }
      if (__isset.Difficulty) {
        field.Name = "Difficulty";
        field.Type = TType.I32;
        field.ID = 4;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(Difficulty);
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder __sb = new StringBuilder("HardwareStatus(");
      bool __first = true;
      if (__isset.DeviceNumber) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("DeviceNumber: ");
        __sb.Append(DeviceNumber);
      }
      if (DeviceName != null && __isset.DeviceName) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("DeviceName: ");
        __sb.Append(DeviceName);
      }
      if (Board != null && __isset.Board) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Board: ");
        __sb.Append(Board);
      }
      if (__isset.Difficulty) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Difficulty: ");
        __sb.Append(Difficulty);
      }
      __sb.Append(")");
      return __sb.ToString();
    }

  }

}
