/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace FusionMiner.Thrift
{
  public enum MaintStepType
  {
    AddFile = 0,
    RemoveFile = 1,
    MinerCommand = 2,
    SystemCommand = 3,
  }
}
