/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace FusionMiner.Thrift
{
  public enum MinerModel
  {
    DigbigSerial = 0,
    DigbigSPI = 1,
    DigbigMini = 2,
  }
}
