/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace FusionMiner.Thrift
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class MinerInfo : TBase
  {
    private string _MAC;
    private long _UniqueId;
    private string _NickName;
    private string _Version;
    private string _SN;

    public string MAC
    {
      get
      {
        return _MAC;
      }
      set
      {
        __isset.MAC = true;
        this._MAC = value;
      }
    }

    public long UniqueId
    {
      get
      {
        return _UniqueId;
      }
      set
      {
        __isset.UniqueId = true;
        this._UniqueId = value;
      }
    }

    public string NickName
    {
      get
      {
        return _NickName;
      }
      set
      {
        __isset.NickName = true;
        this._NickName = value;
      }
    }

    public string Version
    {
      get
      {
        return _Version;
      }
      set
      {
        __isset.Version = true;
        this._Version = value;
      }
    }

    public string SN
    {
      get
      {
        return _SN;
      }
      set
      {
        __isset.SN = true;
        this._SN = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool MAC;
      public bool UniqueId;
      public bool NickName;
      public bool Version;
      public bool SN;
    }

    public MinerInfo() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.String) {
              MAC = iprot.ReadString();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.I64) {
              UniqueId = iprot.ReadI64();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 3:
            if (field.Type == TType.String) {
              NickName = iprot.ReadString();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 4:
            if (field.Type == TType.String) {
              Version = iprot.ReadString();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 5:
            if (field.Type == TType.String) {
              SN = iprot.ReadString();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("MinerInfo");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (MAC != null && __isset.MAC) {
        field.Name = "MAC";
        field.Type = TType.String;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(MAC);
        oprot.WriteFieldEnd();
      }
      if (__isset.UniqueId) {
        field.Name = "UniqueId";
        field.Type = TType.I64;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        oprot.WriteI64(UniqueId);
        oprot.WriteFieldEnd();
      }
      if (NickName != null && __isset.NickName) {
        field.Name = "NickName";
        field.Type = TType.String;
        field.ID = 3;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(NickName);
        oprot.WriteFieldEnd();
      }
      if (Version != null && __isset.Version) {
        field.Name = "Version";
        field.Type = TType.String;
        field.ID = 4;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(Version);
        oprot.WriteFieldEnd();
      }
      if (SN != null && __isset.SN) {
        field.Name = "SN";
        field.Type = TType.String;
        field.ID = 5;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(SN);
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder __sb = new StringBuilder("MinerInfo(");
      bool __first = true;
      if (MAC != null && __isset.MAC) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("MAC: ");
        __sb.Append(MAC);
      }
      if (__isset.UniqueId) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("UniqueId: ");
        __sb.Append(UniqueId);
      }
      if (NickName != null && __isset.NickName) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("NickName: ");
        __sb.Append(NickName);
      }
      if (Version != null && __isset.Version) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Version: ");
        __sb.Append(Version);
      }
      if (SN != null && __isset.SN) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("SN: ");
        __sb.Append(SN);
      }
      __sb.Append(")");
      return __sb.ToString();
    }

  }

}
