/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace FusionMiner.Thrift
{
  public enum PoolType
  {
    Test = 0,
    Stratum = 1,
    GetWork = 2,
  }
}
