/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace FusionMiner.Thrift
{
  public enum PoolStrategyType
  {
    FailOver = 0,
    LoadBalance = 1,
  }
}
